name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none

stages:
  - template: templates/template-branch-policy-validation.yml
    parameters:
      targetBranchName: "refs/heads/production"
      allowedSourceBranchName: "refs/heads/qa"